### ISSUE TITLE
Use PAT to push  to servicecanary

### ISSUE THREAD

**Issue by GrayEye** [pennsignals/servicetemplate#1]
Cruft create succeeds.
Pre-commit succeeds.
Git init succeeds.
Git config credential.helper succeeds.

Git push fails: `fatal: could not read Password for 'https://***@github.com': No such device or address`

**Comment by jlubken** [comment]
The auth tokens used by nomad to pull docker images from ghcr.io are base64 encoded.

The PAT required by the credential helper is NOT the base64 encoded auth token, but the base64 decoded PAT "password" component urlencoded.

**Comment by jlubken** [comment]
... And the PAT needs to have appropriate scope too. Adding pennsignals123 to the servicecanary doesn't do all that is needed.
