### ISSUE TITLE
Update service template predict/dockerfile

### ISSUE THREAD

**Issue by GrayEye** [pennsignals/servicetemplate#4]
service template is missing some of predict/dockerfile apt-get
`apt-get -qq install --yes --no-install-recommends \
        build-essential \
        freetds-dev \
        git \
        libgomp1 \
        libpq-dev \
        libssl-dev \
        libyaml-dev \
        tini \`

**Comment by jlubken** [comment]
Updated ./predict/dockerfile and ./jupyterlab/dockerfile binaries to match library installs. Vim-tiny and nano-tiny are not installed in the predict containers.

Conda (mamba) invokes pip through ./jupyterlab/environment.yml, while predict invokes pip directly.
